### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by uschmidt83** [seung-lab/euclidean-distance-transform-3d#16]
First of all, thank you for providing this useful tool!

I see that you're providing pre-compiled binaries ([wheels](https://pypi.org/project/edt/#files)) on PyPI for macOS and Linux. Do you plan to also do that for Windows?

I'm currently also investigating how to provide wheels for my Python package and found [cibuildwheel](https://github.com/joerick/cibuildwheel), which looks promising.

PS: I noticed that your [setup.py](https://github.com/seung-lab/euclidean-distance-transform-3d/blob/master/python/setup.py) includes compiler flags that do not work with the C++ compiler on Windows. Fortunately, I found that they're simply ignored and the compilation still succeeds.

Best,
Uwe

**Comment by william-silversmith** [comment]
Hi Uwe,

It's certainly conceivable to produce binaries but I haven't ever done any
windows programming. I recently got a Windows VM and MSVC but I'm still
learning how to use it on and off. It might be a bit.

Sorry about that.

Will

**Comment by uschmidt83** [comment]
Hi Will,

thanks for the quick reply! I'm also a novice when it comes to doing development on Windows. But the good thing is that your code apparently just compiles fine on Windows already. I've successfully done a quick test, but don't know if all the functionality works as expected though.

How do you currently build the wheels that you distribute via PyPI?

Best,
Uwe

**Comment by william-silversmith** [comment]
I think FAANG developers would make fun of me, but currently it's
completely manual. I build Linux binaries in a docker with g++ on either an
Ubuntu or Mac OS machine. For Mac binaries, the OS is proprietary so I
build on whatever OS version I have using clang on the command line.

**Comment by uschmidt83** [comment]
> I think FAANG developers would make fun of me, but currently it's completely manual.

That's completely reasonable, especially if you don't have to do it often. Setting up such DevOps stuff also takes time.

**Comment by william-silversmith** [comment]
Oh hey look at that. I was able to use powershell to build and upload a 64-bit binary for python37. Give it a looksie.

**Comment by william-silversmith** [comment]
Ok I also have Python3.6 uploaded as well. I had some problems with 3.5 (missing some component in the linker unrelated to this library). Let me know how they are. I am a little concerned about the optimization level. The automated tests are running slowly, however, it's also in a VM.

**Comment by uschmidt83** [comment]
Thank you, Will!

Unfortunately, I wasn't yet able to gain access to a Windows machine to test this.
I'll be away for the next two weeks and hope to resume my work on this then.

**Comment by william-silversmith** [comment]
I'm going to close this issue assuming that the Windows binaries are working in a few days unless there are objections. Happy computing!

**Comment by uschmidt83** [comment]
The Windows wheel for Python 3.6 does indeed work, see [my test here](https://ci.appveyor.com/project/UweSchmidt/stardist-mg8dq/build/job/bdyivjsso1y2pir6).

**Comment by william-silversmith** [comment]
Thank you for the tests! Glad it's working :)
