### ISSUE TITLE
Missing file threadpool.h

### ISSUE THREAD

**Issue by arc130** [seung-lab/euclidean-distance-transform-3d#17]
Thanks for your work. 
When I using"edt.hpp" in cpp, it seems missing file threadpool.h

**Comment by william-silversmith** [comment]
Oops! You can find it here. Just throw it in the same directory: https://github.com/seung-lab/euclidean-distance-transform-3d/blob/master/python/threadpool.h

**Comment by william-silversmith** [comment]
I think this would probably be nicer as a single hpp file, but I copied threadpool.h to the cpp directory now.

**Comment by william-silversmith** [comment]
Looks like the test.cpp file compiles and runs. Please reopen if you have other concerns!

**Comment by arc130** [comment]
Thanks for your response. 
I find your code require C++11, and can not be used in MSVC 100. Can I modify your code so that it can be used on VS2010, or providing me the single thread version?

**Comment by william-silversmith** [comment]
I introduced parallel fairly late. This version from 1.2.4 is single threaded: https://github.com/seung-lab/euclidean-distance-transform-3d/blob/1.2.4/cpp/edt.hpp

**Comment by william-silversmith** [comment]
It seems to compile without c++11 too!

**Comment by arc130** [comment]
Thanks a lot!
