### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by ma-sadeghi** [seung-lab/euclidean-distance-transform-3d#26]
Hi, 

I wonder if you plan on releasing your package on `conda`.

Thanks,
Amin

**Comment by william-silversmith** [comment]
Hi Amin,

Sorry, for some reason I only saw your question now. I haven't been using conda much, but I get this request sometimes. I can try looking into this, but I'm a bit time constrained at the moment.

**Comment by ma-sadeghi** [comment]
Thanks for your reply William. That'd be great. We use your package as a dependency to [ours](https://github.com/PMEAL/porespy). We'd like to publish our package on `conda-forge`, but it seems that they require that all the dependencies be on `conda-forge` as well.

**Comment by william-silversmith** [comment]
We'll find out if this works soon enough. ^_^

https://github.com/conda-forge/staged-recipes/pull/11458

**Comment by william-silversmith** [comment]
I spent some time trying to get this to work, but I'm running into an "OverlinkingError". Do you have experience with releasing compiled binaries on conda-forge? Would you have any advice?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=152323&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0

https://github.com/conda-forge/staged-recipes/pull/11458

**Comment by ma-sadeghi** [comment]
I tried to build it locally, but no luck so far. I mentioned the reviewing team in your PR, they can usually help.

**Comment by william-silversmith** [comment]
It's merged! Give it a try.

**Comment by ma-sadeghi** [comment]
Thanks! Yep, works as advertised!

**Comment by william-silversmith** [comment]
Thanks for pushing me to get conda-forge working. I suspect that this will open the library up to a new community. I might start releasing some of my other libraries over there too.

**Comment by ma-sadeghi** [comment]
Thank you! I just pushed one of our packages [porespy](https://github.com/PMEAL/porespy/), which depends on `edt`, to `conda-forge`. Apparently, they don't like it when dependencies are not on `conda-forge`.
