### ISSUE TITLE
Watershed transform?

### ISSUE THREAD

**Issue by ma-sadeghi** [seung-lab/euclidean-distance-transform-3d#27]
I know this might be out of the scope of your repo, but do you happen to work on writing your own implementation of watershed transform, similar to this repo for edt?

**Comment by william-silversmith** [comment]
I don't unfortunately. In my field, we use a specialization of watershed
that deals with voxel affinitiy graphs. Jan Funkey wrote
https://github.com/funkey/waterz which is based on earlier work by
Aleksander Zlateski whom was previously in my lab. Does that help?

**Comment by ma-sadeghi** [comment]
Sorry for the late reply, I forgot I hadn't replied back. That's great, I'll definitely look into `waterz`. Thanks!
