### ISSUE TITLE
Python 3.9 support?

### ISSUE THREAD

**Issue by ma-sadeghi** [seung-lab/euclidean-distance-transform-3d#31]
Hi, we'd really appreciate it if you could support Python 3.9 as well. We depend on `edt` in our package [`porespy`](https://github.com/PMEAL/porespy). Thanks!

**Comment by william-silversmith** [comment]
Hi, sorry about that! Last time I looked into it, AppVeyor wasn't supporting it but now they do. I'll make a binary.

**Comment by william-silversmith** [comment]
Okay, the binaries should be available on version 2.0.4! Please let me know if there are other features you'd be interested in. porespy is a cool project!

**Comment by ma-sadeghi** [comment]
Great, thanks!

Have you looked into GitHub Actions? Here's an example of how to use GitHub Actions to automate the builds for Linux/macOS/Windows: https://github.com/robbmcleod/pyfastnoisesimd/blob/master/.github/workflows/build.yml

One last request :sweat:: could you also support Python 3.7 on macOS as well? We really appreciate all your help, and we're glad you like `porespy`.

**Comment by william-silversmith** [comment]
Thanks for the link, that's extremely helpful! I'll look into that. I've been extremely annoyed I can't compile 36 and 37 on Mac for recent editions.

**Comment by william-silversmith** [comment]
@ma-sadeghi I just got my old laptop repaired and released binaries for macos py36 and py37. Enjoy! At some point I'll figure out how to get automated builds working.

**Comment by ma-sadeghi** [comment]
@william-silversmith That's great. Really appreciate all your efforts :)
