### ISSUE TITLE
numpy 1.20 deprecation warning

### ISSUE THREAD

**Issue by ma-sadeghi** [seung-lab/euclidean-distance-transform-3d#32]
Hi! Numpy 1.20.1 throws deprecation warnings for the use of `np.bool` instead of `bool`.

**Comment by william-silversmith** [comment]
I'm setting up a new release (2.0.5). I have been looking into getting those 3.6 and 3.7 mac releases working via GHA, but it doesn't seem to like my directory structure + pbr. I've been thinking of simplifying it and removing the `cpp` directory anyway as it is fairly redundant but I want to retain the info in there as some people do use edt.hpp directly in their C++ projects.
