### ISSUE TITLE
Error importing edt

### ISSUE THREAD

**Issue by kevinjohncutler** [seung-lab/euclidean-distance-transform-3d#34]
I am getting the following error when attempting to import edt: 
`numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject `
I am using python 3.8.5 on Ubuntu 20.04. Let me know if there is anything else I can do to help debug.

**Comment by william-silversmith** [comment]
Hi, unfortunately Numpy 1.20 broke binary compatibility. You can either
install from source (pip install edt --no-binary :all:), update numpy to
1.20, or install an older version of edt that was compiled against older
numpy versions.

Sorry about that... I'm not sure the best way to handle this other than
releasing against the most recent numpy.

**Comment by william-silversmith** [comment]
Looks like if you compile against `oldest-supported-numpy` this problem is resolved. I'll have to make a new release so that ABI compatibility is maintained.

**Comment by william-silversmith** [comment]
Recompiled! Please reopen this issue if it still presents a problem. As a bonus, I was able to release universal2 binaries for py38!
