### ISSUE TITLE
Bug in simple 2x2 input

### ISSUE THREAD

**Issue by M-Wieler** [seung-lab/euclidean-distance-transform-3d#41]
This package looks very helpful, but I think I found a bug with my first example:
<pre>
>>> edt.edt(np.array([[1,1], [2,1]]))
array([[      inf, 1.4142135],
       [1.       , 1.       ]], dtype=float32)
</pre>

Version 2.1.2
Installed from .whl
Windows 10

**Comment by william-silversmith** [comment]
Thanks for reporting! I'll look into this.

**Comment by william-silversmith** [comment]
I think I found the issue. There was an off by one error when considering the very last pixel in a column. Just when I was starting to think this library was totally bug free. Ha. I'll release a fix tomorrow.

**Comment by william-silversmith** [comment]
Here's the fix: https://github.com/seung-lab/euclidean-distance-transform-3d/commit/b06636dc50d7a8d90144910240eedab5c1bedab6

**Comment by M-Wieler** [comment]
Thanks a lot. Will you release it as version 2.1.3?

**Comment by william-silversmith** [comment]
Yes, 2.1.3 is building now. It'll be released in an hour or so!
