### ISSUE TITLE
OMP deprecation warning

### ISSUE THREAD

**Issue by ma-sadeghi** [seung-lab/euclidean-distance-transform-3d#45]
Not sure if this is coming from your package, just in case, I've been getting the following warning recently:

```bash
OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
```

**Comment by william-silversmith** [comment]
Hi Dr. Sadeghi, I'm not using OpenMP for parallelism in this package. It's using a custom thread pool wrapper around pthreads. I think the warning should be coming from another package.

**Comment by ma-sadeghi** [comment]
Thank you so much for your quick reply, I'll look into it and will update you here. I'm closing this issue to keep the issue tracker clean.
