### ISSUE TITLE
error installing EDT on python 3.12

### ISSUE THREAD

**Issue by walee-1** [seung-lab/euclidean-distance-transform-3d#48]
I am trying to install EDT in a virtual python 3.12 environment. However, when trying to do so it gives me the error that it failes to build the wheel for edt, I have attached the log files below. Can you kindly tell me what is it that I am doing wrong or if the package is supported for python 3.12?

[edt_error_Log.txt](https://github.com/seung-lab/euclidean-distance-transform-3d/files/13202347/edt_error_Log.txt)

**Comment by william-silversmith** [comment]
Hi! I guess it's time for the yearly package updates. I just uploaded a wheel for MacOS, but it looks like you need Linux. I'll let you know when I've updated the wheel set.

**Comment by william-silversmith** [comment]
These wheels have been available for a couple weeks!
