### ISSUE TITLE
EDT 3D can be much quicker

### ISSUE THREAD

**Issue by pavlo-hilei** [seung-lab/euclidean-distance-transform-3d#51]
I have noticed that parallelization implementation for three-dimensional EDT is not implemented efficiently and can be significantly accelerated. Please check PR https://github.com/seung-lab/euclidean-distance-transform-3d/pull/50

**Comment by william-silversmith** [comment]
This is pretty interesting. I'll take a closer look when I have some time
this week. Thank you for the contribution!

Will
